# Generated by Django 5.2.4 on 2025-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('answer', models.CharField()),
                ('service', models.CharField(choices=[('IT Consultation', 'IT Consultation'), ('Agriculture', 'Agriculture'), ('Facilities Management', 'Facilities Management'), ('Other', 'Other')], default='Other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
