# Generated by Django 5.2.4 on 2025-07-12 23:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter a valid phone number with country code. Example: +233241234567', max_length=128, region='GH')),
                ('service', models.CharField(choices=[('IT Consultation', 'IT Consultation'), ('Agriculture', 'Agriculture'), ('Facilities Management', 'Facilities Management'), ('Other', 'Other')], default='Other', max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
